/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.sso.struts.action;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import java.util.Set;

import javax.servlet.ServletException;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import jp.co.pegatron.domain.model.AuthgrpAuth;
import jp.co.pegatron.domain.model.AuthgrpAuthId;
import jp.co.pegatron.domain.model.Authority;
import jp.co.pegatron.domain.model.Authoritygroup;
import jp.co.pegatron.domain.model.Organization;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.sso.service.AuthSvc;
import com.sso.service.AuthgroupSvc;
import com.sso.service.AuthgrpAuthSvc;
import com.sso.service.OrgSvc;
import com.sso.service.UserSvc;
import com.sso.struts.form.AuthgrpAuthForm;
import com.sso.struts.form.AuthoritygroupForm;
import com.sso.struts.form.OrganizationForm;
import com.ssoserver.common.pagination.Pagination;
import com.ssoserver.utils.GetPropMessage;

/**
 * MyEclipse Struts Creation date: 04-26-2009
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/resource" name="resourceForm"
 *                input="/resource/resource.jsp" scope="request" validate="true"
 */
public class AuthgrpAuthMgrAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		String task = request.getParameter("task");
		if ("prepconf".equals(task)) {
			request.setAttribute("allauths", AuthSvc.getInstance().findAll());
			String authgroupid = request.getParameter("authgroupid");
			Authoritygroup authgroup = AuthgroupSvc.getInstance().findById(
					new Integer(authgroupid));
			AuthgrpAuthForm authgrpAuthForm = (AuthgrpAuthForm) form;
			authgrpAuthForm.setAuthoritygroup(authgroup);
			// 获取该权限组的权限列表
			Set authgrpauths = authgroup.getAuthgrpAuths();
			List<Authority> hasauths = new ArrayList<Authority>();
			for (Object authgrpauth : authgrpauths) {
				hasauths.add(((AuthgrpAuth) authgrpauth).getAuthority());
			}
			request.setAttribute("hasauths", hasauths);
			return mapping.findForward("conf");
		} else if ("conf".equals(task)) {
			String authgroupid = request.getParameter("authgroupid");
			AuthgrpAuthForm authgrpAuthForm = (AuthgrpAuthForm) form;
			Authoritygroup authgroup = AuthgroupSvc.getInstance().findById(
					new Integer(authgroupid));
			AuthgrpAuthSvc.getInstance().deleteByAuthgroupid(
					new Integer(authgroupid));
			String auths = authgrpAuthForm.getAuthstr();
			if (!"".equals(auths)) {
				String[] hasauths = auths.split(",");
				for (int i = 0; i < hasauths.length; i++) {
					Authority auth = AuthSvc.getInstance().findById(
							new Integer(hasauths[i]));
					AuthgrpAuthId id = new AuthgrpAuthId();
					id.setAuthgroupid(authgroup.getAuthgroupid());
					id.setAuthid(auth.getAuthid());
					id.setMetaauthid(auth.getMetaauthority().getMetaauthid());
					id.setResid(auth.getResource().getResid());
					AuthgrpAuth authgrpAuth = new AuthgrpAuth(id, authgroup,
							auth);
					AuthgrpAuthSvc.getInstance().merge(authgrpAuth);
				}
			}
			return mapping.findForward("safeSuc");
		} else if ("view".equals(task)) {
			// 未需求
		} else if ("add".equals(task)) {
			// 未需求
		} else if ("delete".equals(task)) {
			// 未需求
		} else if ("edit".equals(task)) {
			// 未需求
		} else if ("update".equals(task)) {
			// 未需求
		} else if ("search".equals(task)) {
			// 未需求
		}
		return null;
	}
}