/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package jp.co.pegatron.struts.form;

import java.util.Date;

import javax.servlet.http.HttpServletRequest;

import jp.co.pegatron.domain.model.Contact;
import jp.co.pegatron.service.RepairOrderSvc;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/**
 * MyEclipse Struts Creation date: 02-28-2010
 * 
 * XDoclet definition:
 * 
 * @struts.form name="ContactForm"
 */
public class ContactForm extends ActionForm {

	private Contact contact;
	private String username;
	private String repairorderid;
	private Date contactdatetime;
	private String[] contactvalidate = new String[0];;
	private String customrequire;
	private String customresponse;
	private String repairorderstate;
	private String note;

	public ContactForm() {
		contact = new Contact();
	}

	/**
	 * @return the contact
	 */
	public Contact getContact() {
		contact.setContactdatetime(new Date());
		contact.setContactvalidate("" + getContactvalidateInt());
		contact.setCustomrequire(customrequire);
		contact.setCustomresponse(customresponse);
		contact.setNote(note);
		contact.setRepairorder(RepairOrderSvc.getInstance().findById(
				new Integer(repairorderid)));
		return contact;
	}

	/**
	 * @param contact
	 *            the contact to set
	 */
	public void setContact(Contact contact) {
		this.contact = contact;
	}

	/**
	 * @return the username
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * @param username
	 *            the username to set
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * @return the repairorderid
	 */
	public String getRepairorderid() {
		return repairorderid;
	}

	/**
	 * @param repairorderid
	 *            the repairorderid to set
	 */
	public void setRepairorderid(String repairorderid) {
		this.repairorderid = repairorderid;
	}

	/**
	 * @return the contactdatetime
	 */
	public Date getContactdatetime() {
		return contactdatetime;
	}

	/**
	 * @param contactdatetime
	 *            the contactdatetime to set
	 */
	public void setContactdatetime(Date contactdatetime) {
		this.contactdatetime = contactdatetime;
	}

	/**
	 * @return the contactvalidate
	 */
	public String[] getContactvalidate() {
		return contactvalidate;
	}

	/**
	 * @return the contactvalidate
	 */
	public int getContactvalidateInt() {
		int validateInt = 0;
		for (int i = 0; i < contactvalidate.length; i++) {
			validateInt += new Integer(contactvalidate[i]).intValue();
		}
		return validateInt;
	}

	/**
	 * @param contactvalidate
	 *            the contactvalidate to set
	 */
	public void setContactvalidate(String[] contactvalidate) {
		this.contactvalidate = contactvalidate;
	}

	/**
	 * @return the customresponse
	 */
	public String getCustomresponse() {
		return customresponse;
	}

	/**
	 * @param customresponse
	 *            the customresponse to set
	 */
	public void setCustomresponse(String customresponse) {
		this.customresponse = customresponse;
	}

	/**
	 * @return the repairorderstate
	 */
	public String getRepairorderstate() {
		return repairorderstate;
	}

	/**
	 * @param repairorderstate
	 *            the repairorderstate to set
	 */
	public void setRepairorderstate(String repairorderstate) {
		this.repairorderstate = repairorderstate;
	}

	/**
	 * @return the customrequire
	 */
	public String getCustomrequire() {
		return customrequire;
	}

	/**
	 * @param customrequire
	 *            the customrequire to set
	 */
	public void setCustomrequire(String customrequire) {
		this.customrequire = customrequire;
	}

	/**
	 * @return the note
	 */
	public String getNote() {
		return note;
	}

	/**
	 * @param note
	 *            the note to set
	 */
	public void setNote(String note) {
		this.note = note;
	}

	/**
	 * Method validate
	 * 
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/**
	 * Method reset
	 * 
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}
}