package com.sso.struts.action;

/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
import java.io.IOException;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import jp.co.pegatron.hibernate.EnumUserState;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.ssoserver.business.userMgr.UserMgr;
import com.ssoserver.common.rmi.UserMgrFactory;

/**
 * MyEclipse Struts Creation date: 11-24-2008
 * 
 * XDoclet definition:
 * 
 * @struts.action validate="true"
 */
public class LogonMgrAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 * @throws IOException
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
			throws IOException {
		String task = request.getParameter("task");
		if ("logon".equals(task)) {
			String isLogon = request.getSession().getAttribute(
					EnumUserState.onLine.toString()).toString();
			if (isLogon == null || "".equals(isLogon)
					|| "false".equals(isLogon)) {
				return mapping.findForward("logonPage");
			} else {
				String accessnetsite = request.getParameter("accessnetsite");
				if (accessnetsite != null && !accessnetsite.equals("")) {
					response.sendRedirect(accessnetsite);
					return null;
				}
				return mapping.findForward("defaultPage");
			}
		} else if ("logout".equals(task)) {
			UserMgr userMgr = UserMgrFactory.getUserMgr();
			userMgr.logout(request.getSession().getId());
			return mapping.findForward("refresh");
		}
		return null;
	}
}