/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.sso.struts.form;

import javax.servlet.http.HttpServletRequest;

import jp.co.pegatron.domain.model.Authoritygroup;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

import com.ssoserver.utils.FormatDate;

/**
 * MyEclipse Struts Creation date: 04-26-2009
 * 
 * XDoclet definition:
 * 
 * @struts.form name="resourceForm"
 */
public class AuthoritygroupForm extends ActionForm {
	private String task;
	private Authoritygroup authoritygroup;
	private String authgroupid;
	private String authgroupname;
	private String authgroupcreatetime;
	private String authgroupdiscription;

	/**
	 * @return the authoritygroup
	 */
	public Authoritygroup getAuthoritygroup() {
		authoritygroup = new Authoritygroup();
		return this.buildAuthoritygroup(authoritygroup);
	}

	public Authoritygroup buildAuthoritygroup(Authoritygroup authoritygroup) {
		if (authgroupid != null && !"".equals(authgroupid)) {
			authoritygroup.setAuthgroupid(new Integer(authgroupid));
		}
		authoritygroup.setAuthgroupname(authgroupname);
		authoritygroup.setAuthgroupdiscription(authgroupdiscription);
		if (authgroupcreatetime != null && !"".equals(authgroupcreatetime)) {
			authoritygroup.setAuthgroupcreatetime(FormatDate
					.parseStringToDateTime(authgroupcreatetime));
		}
		return authoritygroup;
	}

	/**
	 * @param authoritygroup
	 *            the authoritygroup to set
	 */
	public void setAuthoritygroup(Authoritygroup authoritygroup) {
		this.authoritygroup = authoritygroup;
		authgroupid = authoritygroup.getAuthgroupid().toString();
		authgroupname = authoritygroup.getAuthgroupname();
		authgroupdiscription = authoritygroup.getAuthgroupdiscription();
		authgroupcreatetime = FormatDate.formatDateTimeToString(authoritygroup
				.getAuthgroupcreatetime());
	}

	/**
	 * @return the task
	 */
	public String getTask() {
		return task;
	}

	/**
	 * @param task
	 *            the task to set
	 */
	public void setTask(String task) {
		this.task = task;
	}

	/**
	 * @return the authgroupid
	 */
	public String getAuthgroupid() {
		return authgroupid;
	}

	/**
	 * @param authgroupid
	 *            the authgroupid to set
	 */
	public void setAuthgroupid(String authgroupid) {
		this.authgroupid = authgroupid;
	}

	/**
	 * @return the authgroupname
	 */
	public String getAuthgroupname() {
		return authgroupname;
	}

	/**
	 * @param authgroupname
	 *            the authgroupname to set
	 */
	public void setAuthgroupname(String authgroupname) {
		this.authgroupname = authgroupname;
	}

	/**
	 * @return the authgroupcreatetime
	 */
	public String getAuthgroupcreatetime() {
		return authgroupcreatetime;
	}

	/**
	 * @param authgroupcreatetime
	 *            the authgroupcreatetime to set
	 */
	public void setAuthgroupcreatetime(String authgroupcreatetime) {
		this.authgroupcreatetime = authgroupcreatetime;
	}

	/**
	 * @return the authgroupdiscription
	 */
	public String getAuthgroupdiscription() {
		return authgroupdiscription;
	}

	/**
	 * @param authgroupdiscription
	 *            the authgroupdiscription to set
	 */
	public void setAuthgroupdiscription(String authgroupdiscription) {
		this.authgroupdiscription = authgroupdiscription;
	}

	/**
	 * Method validate
	 * 
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/**
	 * Method reset
	 * 
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}
}