/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.sso.struts.form;

import javax.servlet.http.HttpServletRequest;

import jp.co.pegatron.domain.model.Authority;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

import com.sso.service.MetaauthSvc;
import com.sso.service.ResourceSvc;

/**
 * MyEclipse Struts Creation date: 04-26-2009
 * 
 * XDoclet definition:
 * 
 * @struts.form name="resourceForm"
 */

public class AuthorityForm extends ActionForm {
	private String task;
	private Authority authority;
	private String resid;
	private String metaauthid;
	private String authid;
	private String authdiscription;

	/**
	 * @return the authority
	 */
	public Authority getAuthority() {
		authority = new Authority();
		return this.buildAuthority(authority);
	}

	public Authority buildAuthority(Authority authority) {
		if (authid != null && !"".equals(authid)) {
			authority.setAuthid(new Integer(authid));
		}
		if (resid != null && !"".equals(resid)) {
			authority.setResource(ResourceSvc.getInstance().findById(
					new Integer(resid)));
		}
		if (metaauthid != null && !"".equals(metaauthid)) {
			authority.setMetaauthority(MetaauthSvc.getIntance().findById(
					new Integer(metaauthid)));
		}
		authority.setAuthdiscription(authdiscription);
		return authority;
	}

	/**
	 * @param authority
	 *            the authority to set
	 */
	public void setAuthority(Authority authority) {
		this.authority = authority;
		authid = authority.getAuthid().toString();
		resid = authority.getResource().getResid().toString();
		metaauthid = authority.getMetaauthority().getMetaauthid().toString();
		authdiscription = authority.getAuthdiscription();
	}

	/**
	 * @return the task
	 */
	public String getTask() {
		return task;
	}

	/**
	 * @param task
	 *            the task to set
	 */
	public void setTask(String task) {
		this.task = task;
	}

	/**
	 * @return the resid
	 */
	public String getResid() {
		return resid;
	}

	/**
	 * @param resid
	 *            the resid to set
	 */
	public void setResid(String resid) {
		this.resid = resid;
	}

	/**
	 * @return the metaauthid
	 */
	public String getMetaauthid() {
		return metaauthid;
	}

	/**
	 * @param metaauthid
	 *            the metaauthid to set
	 */
	public void setMetaauthid(String metaauthid) {
		this.metaauthid = metaauthid;
	}

	/**
	 * @return the authid
	 */
	public String getAuthid() {
		return authid;
	}

	/**
	 * @param authid
	 *            the authid to set
	 */
	public void setAuthid(String authid) {
		this.authid = authid;
	}

	/**
	 * @return the authdiscription
	 */
	public String getAuthdiscription() {
		return authdiscription;
	}

	/**
	 * @param authdiscription
	 *            the authdiscription to set
	 */
	public void setAuthdiscription(String authdiscription) {
		this.authdiscription = authdiscription;
	}

	/**
	 * Method validate
	 * 
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/**
	 * Method reset
	 * 
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}
}