/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.sso.struts.form;

import javax.servlet.http.HttpServletRequest;

import jp.co.pegatron.domain.model.Authoritygroup;
import jp.co.pegatron.domain.model.User;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

import com.ssoserver.utils.FormatDate;

/**
 * MyEclipse Struts Creation date: 04-26-2009
 * 
 * XDoclet definition:
 * 
 * @struts.form name="resourceForm"
 */
public class AuthgrpUserForm extends ActionForm {
	private String task;
	private String userid;
	private String username;
	private String allauthgrps;
	private String hasauthgrps;
	private String authgrpstr;

	public void setUser(User user) {
		this.userid = user.getUserid().toString();
		this.username = user.getUsername();
	}

	/**
	 * @return the task
	 */
	public String getTask() {
		return task;
	}

	/**
	 * @param task
	 *            the task to set
	 */
	public void setTask(String task) {
		this.task = task;
	}

	/**
	 * @return the userid
	 */
	public String getUserid() {
		return userid;
	}

	/**
	 * @param userid
	 *            the userid to set
	 */
	public void setUserid(String userid) {
		this.userid = userid;
	}

	/**
	 * @return the username
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * @param username
	 *            the username to set
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * @return the allauthgrps
	 */
	public String getAllauthgrps() {
		return allauthgrps;
	}

	/**
	 * @param allauthgrps
	 *            the allauthgrps to set
	 */
	public void setAllauthgrps(String allauthgrps) {
		this.allauthgrps = allauthgrps;
	}

	/**
	 * @return the hasauthgrps
	 */
	public String getHasauthgrps() {
		return hasauthgrps;
	}

	/**
	 * @param hasauthgrps
	 *            the hasauthgrps to set
	 */
	public void setHasauthgrps(String hasauthgrps) {
		this.hasauthgrps = hasauthgrps;
	}

	/**
	 * @return the authgrpstr
	 */
	public String getAuthgrpstr() {
		return authgrpstr;
	}

	/**
	 * @param authgrpstr
	 *            the authgrpstr to set
	 */
	public void setAuthgrpstr(String authgrpstr) {
		this.authgrpstr = authgrpstr;
	}

	/**
	 * Method validate
	 * 
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/**
	 * Method reset
	 * 
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}
}