/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.sso.struts.form;

import javax.servlet.http.HttpServletRequest;

import jp.co.pegatron.domain.model.Authoritygroup;
import jp.co.pegatron.domain.model.Organization;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

import com.sso.service.AuthgroupSvc;
import com.sso.service.UserSvc;

/**
 * MyEclipse Struts Creation date: 04-26-2009
 * 
 * XDoclet definition:
 * 
 * @struts.form name="resourceForm"
 */
public class OrganizationForm extends ActionForm {
	private String task;
	private Organization org;
	private String orgid;
	private String authgroupid;
	private String orgname;
	private String manager;
	private Integer uplevel;
	private String orgdiscription;

	/**
	 * @return the org
	 */
	public Organization getOrg() {
		org = new Organization();
		return buildOrg(org);
	}

	public Organization buildOrg(Organization org) {
		if (orgid != null && !"".equals(orgid)) {
			org.setOrgid(new Integer(orgid));
		}
		if (authgroupid != null && !"".equals(authgroupid)) {
			Authoritygroup authoritygroup = AuthgroupSvc.getInstance()
					.findById(new Integer(authgroupid));
			org.setAuthoritygroup(authoritygroup);
		}
		org.setOrgname(orgname);
		if (manager != null && !"".equals(manager)) {
			org.setManager(new Integer(manager));
		}
		org.setUplevel(new Integer(uplevel));
		org.setOrgdiscription(orgdiscription);
		return org;
	}

	/**
	 * @param org
	 *            the org to set
	 */
	public void setOrg(Organization org) {
		this.org = org;
		this.orgid = org.getOrgid().toString();
		if (org.getAuthoritygroup() != null) {
			this.authgroupid = org.getAuthoritygroup().getAuthgroupid()
					.toString();
		}
		this.orgname = org.getOrgname();
		this.manager = org.getManager().toString();
		this.uplevel = org.getUplevel();
		this.orgdiscription = org.getOrgdiscription();
	}

	/**
	 * @return the task
	 */
	public String getTask() {
		return task;
	}

	/**
	 * @param task
	 *            the task to set
	 */
	public void setTask(String task) {
		this.task = task;
	}

	/**
	 * @return the authgroupid
	 */
	public String getAuthgroupid() {
		return authgroupid;
	}

	/**
	 * @param authgroupid
	 *            the authgroupid to set
	 */
	public void setAuthgroupid(String authgroupid) {
		this.authgroupid = authgroupid;
	}

	/**
	 * @return the orgid
	 */
	public String getOrgid() {
		return orgid;
	}

	/**
	 * @param orgid
	 *            the orgid to set
	 */
	public void setOrgid(String orgid) {
		this.orgid = orgid;
	}

	/**
	 * @return the orgname
	 */
	public String getOrgname() {
		return orgname;
	}

	/**
	 * @param orgname
	 *            the orgname to set
	 */
	public void setOrgname(String orgname) {
		this.orgname = orgname;
	}

	/**
	 * @return the manager
	 */
	public String getManager() {
		return manager;
	}

	/**
	 * @param manager
	 *            the manager to set
	 */
	public void setManager(String manager) {
		this.manager = manager;
	}

	/**
	 * @return the uplevel
	 */
	public Integer getUplevel() {
		return uplevel;
	}

	/**
	 * @param uplevel
	 *            the uplevel to set
	 */
	public void setUplevel(Integer uplevel) {
		this.uplevel = uplevel;
	}

	/**
	 * @return the orgdiscription
	 */
	public String getOrgdiscription() {
		return orgdiscription;
	}

	/**
	 * @param orgdiscription
	 *            the orgdiscription to set
	 */
	public void setOrgdiscription(String orgdiscription) {
		this.orgdiscription = orgdiscription;
	}

	/**
	 * Method validate
	 * 
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/**
	 * Method reset
	 * 
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}
}