/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.sso.struts.form;

import javax.servlet.http.HttpServletRequest;

import jp.co.pegatron.domain.model.Authoritygroup;
import jp.co.pegatron.domain.model.Organization;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

import com.sso.service.AuthgroupSvc;
import com.sso.service.UserSvc;

/**
 * MyEclipse Struts Creation date: 04-26-2009
 * 
 * XDoclet definition:
 * 
 * @struts.form name="resourceForm"
 */
public class OrgUserForm extends ActionForm {
	private String task;
	private String orgid;
	private String orgname;
	private String allusers;
	private String members;
	private String memberstr;

	/**
	 * @param org
	 *            the org to set
	 */
	public void setOrg(Organization org) {
		this.orgid = org.getOrgid().toString();
		this.orgname = org.getOrgname();
	}

	/**
	 * @return the task
	 */
	public String getTask() {
		return task;
	}

	/**
	 * @param task
	 *            the task to set
	 */
	public void setTask(String task) {
		this.task = task;
	}

	/**
	 * @return the orgid
	 */
	public String getOrgid() {
		return orgid;
	}

	/**
	 * @param orgid
	 *            the orgid to set
	 */
	public void setOrgid(String orgid) {
		this.orgid = orgid;
	}

	/**
	 * @return the orgname
	 */
	public String getOrgname() {
		return orgname;
	}

	/**
	 * @param orgname
	 *            the orgname to set
	 */
	public void setOrgname(String orgname) {
		this.orgname = orgname;
	}

	/**
	 * @return the allusers
	 */
	public String getAllusers() {
		return allusers;
	}

	/**
	 * @param allusers
	 *            the allusers to set
	 */
	public void setAllusers(String allusers) {
		this.allusers = allusers;
	}

	/**
	 * @return the members
	 */
	public String getMembers() {
		return members;
	}

	/**
	 * @param members
	 *            the members to set
	 */
	public void setMembers(String members) {
		this.members = members;
	}

	/**
	 * @return the memberstr
	 */
	public String getMemberstr() {
		return memberstr;
	}

	/**
	 * @param memberstr
	 *            the memberstr to set
	 */
	public void setMemberstr(String memberstr) {
		this.memberstr = memberstr;
	}

	/**
	 * Method validate
	 * 
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/**
	 * Method reset
	 * 
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}
}