/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.sso.struts.form;

import javax.servlet.ServletRequest;
import javax.servlet.http.HttpServletRequest;

import jp.co.pegatron.domain.model.Resource;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/**
 * MyEclipse Struts Creation date: 04-26-2009
 * 
 * XDoclet definition:
 * 
 * @struts.form name="resourceForm"
 */
public class ResourceForm extends ActionForm {
	private Resource resource;

	private String task;
	/*
	 * Generated fields
	 */

	/** resdiscription property */
	private String resdiscription;

	/** resid property */
	private String resid;

	/** resname property */
	private String resname;

	/**
	 * @return the resource
	 */
	public Resource getResource() {
		resource = new Resource();
		this.buildResource(resource);
		return resource;
	}

	public void buildResource(Resource resource) {
		if (resid != null && !"".equals(resid)) {
			resource.setResid(new Integer(resid));
		}
		resource.setResname(resname);
		resource.setResdiscription(resdiscription);
	}

	/**
	 * @param resource
	 *            the resource to set
	 */
	public void setResource(Resource resource) {
		this.resource = resource;
		resid = resource.getResid().toString();
		resname = resource.getResname();
		resdiscription = resource.getResdiscription();
	}

	/**
	 * Method validate
	 * 
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/**
	 * Method reset
	 * 
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/**
	 * Method validate
	 * 
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping, ServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/**
	 * Method reset
	 * 
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, ServletRequest request) {
		// TODO Auto-generated method stub
	}

	/**
	 * @return the resid
	 */
	public String getResid() {
		return resid;
	}

	/**
	 * @param resid
	 *            the resid to set
	 */
	public void setResid(String resid) {
		this.resid = resid;
	}

	/**
	 * @return the resname
	 */
	public String getResname() {
		return resname;
	}

	/**
	 * @param resname
	 *            the resname to set
	 */
	public void setResname(String resname) {
		this.resname = resname;
	}

	/**
	 * @return the resdiscription
	 */
	public String getResdiscription() {
		return resdiscription;
	}

	/**
	 * @param resdiscription
	 *            the resdiscription to set
	 */
	public void setResdiscription(String resdiscription) {
		this.resdiscription = resdiscription;
	}

	/**
	 * @return the task
	 */
	public String getTask() {
		return task;
	}

	/**
	 * @param task
	 *            the task to set
	 */
	public void setTask(String task) {
		this.task = task;
	}

}