/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package jp.co.pegatron.struts.form;

import javax.servlet.http.HttpServletRequest;

import jp.co.pegatron.domain.model.Agent;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;

/**
 * @author HTB
 */
public class AgentForm extends ActionForm {
	private Agent agent;
	private String task;// 用于判断验证
	private Integer agentid;
	private String agentname;
	private String agentphone;
	private String agentemail;

	public AgentForm() {
		agent = new Agent();
	}

	/**
	 * @return the agent
	 */
	public Agent getAgent() {
		this.buildAgent(agent);
		return agent;
	}

	public void buildAgent(Agent agent) {
		if (agentid != null && !"".equals(agentid)) {
			agent.setAgentid(new Integer(agentid));
		}
		agent.setAgentname(agentname);
		agent.setAgentphone(agentphone);
		agent.setAgentemail(agentemail);
	}

	/**
	 * @param agent
	 *            the agent to set
	 */
	public void setAgent(Agent agent) {
		this.agent = agent;
		agentid = agent.getAgentid();
		agentname = agent.getAgentname();
		agentphone = agent.getAgentphone();
		agentemail = agent.getAgentemail();
	}

	/**
	 * @return the task
	 */
	public String getTask() {
		return task;
	}

	/**
	 * @param task
	 *            the task to set
	 */
	public void setTask(String task) {
		this.task = task;
	}

	/**
	 * @return the agentid
	 */
	public Integer getAgentid() {
		return agentid;
	}

	/**
	 * @param agentid
	 *            the agentid to set
	 */
	public void setAgentid(Integer agentid) {
		this.agentid = agentid;
	}

	/**
	 * @return the agentname
	 */
	public String getAgentname() {
		return agentname;
	}

	/**
	 * @param agentname
	 *            the agentname to set
	 */
	public void setAgentname(String agentname) {
		this.agentname = agentname;
	}

	/**
	 * @return the agentphone
	 */
	public String getAgentphone() {
		return agentphone;
	}

	/**
	 * @param agentphone
	 *            the agentphone to set
	 */
	public void setAgentphone(String agentphone) {
		this.agentphone = agentphone;
	}

	/**
	 * @return the agentemail
	 */
	public String getAgentemail() {
		return agentemail;
	}

	/**
	 * @param agentemail
	 *            the agentemail to set
	 */
	public void setAgentemail(String agentemail) {
		this.agentemail = agentemail;
	}

	/**
	 * Method validate
	 * 
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		if ("add".equals(task) || "update".equals(task)) {
			ActionErrors errors = new ActionErrors();
			if (agentname == null || "".equals(agentname)) {
				errors.add("agentname", new ActionMessage(
						"agentForm.agentnameNull", "代理商名不能为空!"));
			} else if (agentname.matches("^[a-zA-Z][a-zA-Z0-9_]{4,19}$")) {
				errors.add("userName", new ActionMessage(
						"userinfoForm.usernameError",
						"代理商名要以字母开头，允许5-20字节，允许字母数字下划线"));
			}
			if (!errors.isEmpty()) {
				return errors;
			}
		}
		return null;
	}

	/**
	 * Method reset
	 * 
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}
}