/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package jp.co.pegatron.struts.form;

import java.util.Date;

import javax.servlet.http.HttpServletRequest;

import jp.co.pegatron.domain.model.Bulletin;
import jp.co.pegatron.hibernate.EnumBulletinType;
import jp.co.pegatron.service.UserSvc;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;

import com.ssoserver.utils.FormatDate;

/**
 * @author HTB
 */
public class BulletinForm extends ActionForm {
	private String task;
	private Bulletin bulletin;
	private String bulletinid;
	private String userid;
	private String publishdate;
	private String bulletintitle;
	private String content;
	private String bulletintype;

	public BulletinForm() {
		bulletin = new Bulletin();
	}

	/**
	 * @return the bulletin
	 */
	public Bulletin getBulletin() {
		return this.buildBulletin(this.bulletin);
	}

	public Bulletin buildBulletin(Bulletin bulletin) {
		if (publishdate == null || "".equals(publishdate)) {
			bulletin.setPublishdate(new Date());
		}
		bulletin.setBulletintitle(bulletintitle);
		bulletin.setBulletintype(EnumBulletinType.valueOf(bulletintype));
		bulletin.setContent(content);
		return bulletin;
	}

	/**
	 * @param bulletin
	 *            the bulletin to set
	 */
	public void setBulletin(Bulletin bulletin) {
		this.bulletin = bulletin;
		bulletinid = bulletin.getBulletinid().toString();
		userid = bulletin.getUser().getUserid().toString();
		publishdate = FormatDate.formatDateToString(bulletin.getPublishdate());
		bulletintitle = bulletin.getBulletintitle();
		content = bulletin.getContent();
		bulletintype = bulletin.getBulletintype().toString();
	}

	/**
	 * @return the bulletinid
	 */
	public String getBulletinid() {
		return bulletinid;
	}

	/**
	 * @param bulletinid
	 *            the bulletinid to set
	 */
	public void setBulletinid(String bulletinid) {
		this.bulletinid = bulletinid;
	}

	/**
	 * @return the userid
	 */
	public String getUserid() {
		return userid;
	}

	/**
	 * @param userid
	 *            the userid to set
	 */
	public void setUserid(String userid) {
		this.userid = userid;
	}

	/**
	 * @return the publishdate
	 */
	public String getPublishdate() {
		return publishdate;
	}

	/**
	 * @param publishdate
	 *            the publishdate to set
	 */
	public void setPublishdate(String publishdate) {
		this.publishdate = publishdate;
	}

	/**
	 * @return the bulletintitle
	 */
	public String getBulletintitle() {
		return bulletintitle;
	}

	/**
	 * @param bulletintitle
	 *            the bulletintitle to set
	 */
	public void setBulletintitle(String bulletintitle) {
		this.bulletintitle = bulletintitle;
	}

	/**
	 * @return the content
	 */
	public String getContent() {
		return content;
	}

	/**
	 * @param content
	 *            the content to set
	 */
	public void setContent(String content) {
		this.content = content;
	}

	/**
	 * @return the bulletintype
	 */
	public String getBulletintype() {
		return bulletintype;
	}

	/**
	 * @param bulletintype
	 *            the bulletintype to set
	 */
	public void setBulletintype(String bulletintype) {
		this.bulletintype = bulletintype;
	}

	/**
	 * @return the task
	 */
	public String getTask() {
		return task;
	}

	/**
	 * @param task
	 *            the task to set
	 */
	public void setTask(String task) {
		this.task = task;
	}

	/**
	 * Method validate
	 * 
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		if ("add".equals(task)) {
			ActionErrors errors = new ActionErrors();
			if (bulletintitle == null || "".equals(bulletintitle)) {
				errors.add("bulletintitle", new ActionMessage(
						"logonForm.bulltitErr", "标题不能为空。"));
			}
			if (content == null || "".equals(content)) {
				errors.add("content", new ActionMessage("logonForm.cttErr",
						"内容不能为空。"));
			}
			return errors.isEmpty() ? null : errors;
		}
		return null;
	}

	/**
	 * Method reset
	 * 
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}
}