/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package jp.co.pegatron.struts.form;

import java.util.Date;

import javax.servlet.http.HttpServletRequest;

import jp.co.pegatron.domain.model.Model;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/**
 * @author HTB
 */
public class ModelForm extends ActionForm {
	private Model model;
	private String task;// 用于判断验证
	private String modelid;
	private String modelname;
	private String modelphoto;
	private String parameter;
	private String linkmark;

	public ModelForm() {
		model = new Model();
	}

	/**
	 * @return the model
	 */
	public Model getModel() {
		this.buildModel(model);
		return model;
	}

	public void buildModel(Model model) {
		if (modelid != null && !"".equals(modelid)) {
			model.setModelid(new Integer(modelid));
		}
		model.setModelname(modelname);
		model.setParameter(parameter);
		model.setLinkmark(linkmark);
	}

	/**
	 * @param model
	 *            the model to set
	 */
	public void setModel(Model model) {
		this.model = model;
		modelid = model.getModelid().toString();
		modelname = model.getModelname();
		parameter = model.getParameter();
		linkmark = model.getLinkmark();
	}

	/**
	 * @return the modelid
	 */
	public String getModelid() {
		return modelid;
	}

	/**
	 * @param modelid
	 *            the modelid to set
	 */
	public void setModelid(String modelid) {
		this.modelid = modelid;
	}

	/**
	 * @return the modelname
	 */
	public String getModelname() {
		return modelname;
	}

	/**
	 * @param modelname
	 *            the modelname to set
	 */
	public void setModelname(String modelname) {
		this.modelname = modelname;
	}

	/**
	 * @return the modelphoto
	 */
	public String getModelphoto() {
		return modelphoto;
	}

	/**
	 * @param modelphoto
	 *            the modelphoto to set
	 */
	public void setModelphoto(String modelphoto) {
		this.modelphoto = modelphoto;
	}

	/**
	 * @return the parameter
	 */
	public String getParameter() {
		return parameter;
	}

	/**
	 * @param parameter
	 *            the parameter to set
	 */
	public void setParameter(String parameter) {
		this.parameter = parameter;
	}

	/**
	 * @return the linkmark
	 */
	public String getLinkmark() {
		return linkmark;
	}

	/**
	 * @param linkmark
	 *            the linkmark to set
	 */
	public void setLinkmark(String linkmark) {
		this.linkmark = linkmark;
	}

	/**
	 * Method validate
	 * 
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/**
	 * Method reset
	 * 
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}
}