/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package jp.co.pegatron.struts.action;

import java.io.IOException;
import java.rmi.RemoteException;
import java.util.Date;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import jp.co.pegatron.domain.model.Bulletin;
import jp.co.pegatron.domain.model.User;
import jp.co.pegatron.service.BulletinSvc;
import jp.co.pegatron.struts.form.BulletinForm;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.ssoserver.business.userMgr.UserMgr;
import com.ssoserver.common.pagination.Pagination;
import com.ssoserver.common.rmi.UserMgrFactory;
import com.ssoserver.utils.GetPropMessage;

/**
 * MyEclipse Struts Creation date: 03-01-2010
 * 
 * XDoclet definition:
 * 
 * @struts.action validate="true"
 */
public class BulletinMgrAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		String task = request.getParameter("task");
		if ("view".equals(task)) {
			Pagination pagination = new Pagination();
			String scope = request.getParameter("scope");
			List bulletinList = null;
			String viewHQLStr;
			if ("community".equals(scope)) {
				viewHQLStr = GetPropMessage.getUTF8Message("cmunBulletin");
			} else if ("repairer".equals(scope)) {
				viewHQLStr = GetPropMessage.getUTF8Message("repairerBulletin");
			} else if ("contacter".equals(scope)) {
				viewHQLStr = GetPropMessage.getUTF8Message("contacterBulletin");
			} else if ("all".equals(scope)) {
				viewHQLStr = GetPropMessage.getUTF8Message("allBulletin");
			} else {
				viewHQLStr = GetPropMessage.getUTF8Message("allBulletin");
			}
			bulletinList = pagination.execute(BulletinSvc.getInstance(),
					viewHQLStr, request, response);
			request.setAttribute("scope", scope);
			request.setAttribute("bulletinList", bulletinList);
			return mapping.findForward("showBulletin");
		} else if ("manage".equals(task)) {
			Pagination pagination = new Pagination();
			String scope = request.getParameter("scope");
			List bulletinList = null;
			String viewHQLStr;
			if ("community".equals(scope)) {
				viewHQLStr = GetPropMessage.getUTF8Message("cmunBulletin");
			} else if ("repairer".equals(scope)) {
				viewHQLStr = GetPropMessage.getUTF8Message("repairerBulletin");
			} else if ("contacter".equals(scope)) {
				viewHQLStr = GetPropMessage.getUTF8Message("contacterBulletin");
			} else if ("all".equals(scope)) {
				viewHQLStr = GetPropMessage.getUTF8Message("allBulletin");
			} else {
				viewHQLStr = GetPropMessage.getUTF8Message("allBulletin");
			}
			bulletinList = pagination.execute(BulletinSvc.getInstance(),
					viewHQLStr, request, response);
			request.setAttribute("scope", scope);
			request.setAttribute("bulletinList", bulletinList);
			return mapping.findForward("mgrBulletin");
		} else if ("add".equals(task)) {
			BulletinForm bulletinForm = (BulletinForm) form;
			Bulletin bulletin = bulletinForm.getBulletin();
			bulletin.setPublishdate(new Date());
			String secKey = request.getSession().getAttribute(UserMgr.SECKEY)
					.toString();
			User user = null;
			try {
				user = UserMgrFactory.getUserMgr().getCurrentUser(secKey);
			} catch (RemoteException e) {
				e.printStackTrace();
			}
			bulletin.setUser(user);
			BulletinSvc.getInstance().save(bulletin);
			return mapping.findForward("safeSuc");
		} else if ("delete".equals(task)) {
			String bulletinid = request.getParameter("bulletinid");
			BulletinSvc.getInstance().deleteByid(new Integer(bulletinid));
			// request.setAttribute(name, o)
			// return mapping.findForward("delSuc");
			try {
				request.getRequestDispatcher("/bulletinMgr.do?task=manage")
						.forward(request, response);
			} catch (ServletException e) {
				e.printStackTrace();
			} catch (IOException e) {
				e.printStackTrace();
			}
			return null;
			// 编辑一个公告
		} else if ("edit".equals(task)) {
			String bulletinid = request.getParameter("bulletinid");
			Bulletin bulletin = BulletinSvc.getInstance().findById(
					new Integer(bulletinid));
			BulletinForm bulletinForm = (BulletinForm) form;
			bulletinForm.setBulletin(bulletin);
			return mapping.findForward("edit");
			// 更新保存一个公告
		} else if ("update".equals(task)) {
			BulletinForm bulletinForm = (BulletinForm) form;
			Bulletin bulletin = BulletinSvc.getInstance().findById(
					new Integer(bulletinForm.getBulletinid()));
			bulletinForm.buildBulletin(bulletin);
			BulletinSvc.getInstance().update(bulletin);
			return mapping.findForward("safeSuc");
		} else if ("search".equals(task)) {
			// 未需求
		}
		return null;
	}
}